# ========================
# SERVIDOR
# ========================
server.port=8081

# ========================
# BASE DE DATOS (Supabase PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vqxblugxfhsiecyhvlgx
spring.datasource.password=MarcoCouRoman1492
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Inicializacion de datos
# ========================
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# ========================
# JWT (Supabase)
# ========================
# app.jwt.secret ya no se usa, ahora usamos JWKS automático para soportar claves ECC
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://vqxblugxfhsiecyhvlgx.supabase.co/auth/v1/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

# ========================
# CORS
# ========================
app.cors.allowed-origins=http://localhost,http://localhost:3000,http://localhost:8000,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083

# ========================
# Nombre de la app
# ========================
spring.application.name=servicio-puntos
