# ========================
# SERVIDOR — el puerto lo define NODE_PORT (default 8081)
# ========================
server.port=${NODE_PORT:8081}

# ========================
# BASE DE DATOS (Supabase PostgreSQL) — compartida por los 3 nodos
# ========================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.vqxblugxfhsiecyhvlgx
spring.datasource.password=MarcoCouRoman1492
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# HikariCP (Connection Pool)
# ========================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# ========================
# Inicializacion de datos
# ========================
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# ========================
# JWT (Supabase)
# ========================
app.jwt.secret=912e2ffd-9948-49c2-9ba8-f786ad24ea85

# ========================
# CORS — permite gateway y Flutter local
# ========================
app.cors.allowed-origins=http://localhost,http://localhost:3000,http://localhost:8000,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://localhost:8083

# ========================
# Nombre de la app
# ========================
spring.application.name=servicio-puntos

# ========================
# BULLY — Algoritmo de Eleccion
# NODE_ID  : identificador numerico de este nodo (1, 2 o 3)
# NODE_PORT: puerto en que escucha este nodo
# NODE_URLS: URLs de TODOS los nodos separados por coma (orden = ID creciente)
# ========================
bully.node-id=${NODE_ID:1}
bully.node-port=${NODE_PORT:8081}
bully.node-urls=${NODE_URLS:http://localhost:8081,http://localhost:8082,http://localhost:8083}
