# ========================
# SERVIDOR
# ========================
server.port=8081

# ========================
# BASE DE DATOS (Supabase PostgreSQL)
# ========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# Inicializacion de datos
# ========================
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# ========================
# JWT (Supabase)
# ========================
# app.jwt.secret ya no se usa, ahora usamos JWKS automático para soportar claves ECC
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

# ========================
# CORS
# ========================
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# ========================
# Nombre de la app
# ========================
spring.application.name=servicio-puntos

