version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin_secure_password}

  postgres-exporter:
    # Cambiamos al contenedor oficial de la comunidad de Prometheus (Soporta Postgres 17)
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      # Usa aquí la cadena de conexión DIRECTA que copiaste en el Paso 1
      - DATA_SOURCE_NAME=postgresql://postgres:[TU_PASSWORD]@db.xxxxxxxxx.supabase.co:5432/postgres?sslmode=disable
      
      # Truco extra: Desactivamos métricas obsoletas de motores viejos para limpiar el log
      - PG_EXPORTER_DISABLE_DEFAULT_METRICS=false

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana

volumes:
  prometheus_data:
  grafana_data:
