version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090" # Solo acceder internamente o restringido por IP en GCE

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000" # Exponer este puerto en el Firewall de Google Cloud
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin_secure_password}

  postgres-exporter:
    # Cambiamos al contenedor oficial de la comunidad de Prometheus (Soporta Postgres 17)
    image: prometheus-community/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      # Usa aquí la cadena de conexión DIRECTA que copiaste en el Paso 1
      - DATA_SOURCE_NAME=postgresql://postgres:[TU_PASSWORD]@db.xxxxxxxxx.supabase.co:5432/postgres?sslmode=disable
      
      # Truco extra: Desactivamos métricas obsoletas de motores viejos para limpiar el log
      - PG_EXPORTER_DISABLE_DEFAULT_METRICS=false
    ports:
      - "9187:9187"

volumes:
  prometheus_data:
  grafana_data:
