steps:
  # 0. Validación y Pruebas
  - name: 'python:3.12-slim'
    id: 'Quality Gate'
    dir: 'servicio_usuarios'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -e

        echo "=========================================="
        echo " Instalando dependencias"
        echo "=========================================="

        pip install -r requirements.txt pytest ruff

        # Intenta limpiar la pantalla (si el terminal lo permite)
        clear || true

        echo ""
        echo "=========================================="
        echo " Ejecutando Ruff"
        echo "=========================================="

        ruff check . --output-format=full

        echo ""
        echo "=========================================="
        echo " Ejecutando Pytest"
        echo "=========================================="

        pytest -vv -ra --tb=short tests/

        echo ""
        echo "=========================================="
        echo " ✅ QUALITY GATE SUPERADO"
        echo "=========================================="

  # 1. Construir la imagen Docker usando el Dockerfile y apuntando a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'servicio_usuarios'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'

  # 2. Subir la imagen al repositorio de Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'servicio_usuarios'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  # 3. Desplegar la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'servicio_usuarios'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'servicio-usuarios'
  _REPO_NAME: 'servicio-usuarios-registry'
  _REGION: 'southamerica-west1'